spring:
  main:
    banner-mode: off
    keep-alive: true
    log-startup-info: false
    lazy-initialization: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: "jdbc:postgresql://${MY_DB_HOST}:${MY_DB_PORT:5432}/${MY_DB_NAME}?currentSchema=${MY_DB_SCHEMA:public}&sslmode=require"
    username: ${MY_DB_USERNAME}
    password: ${MY_DB_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: "classpath:db/changelog/_main.yaml"
    database-change-log-table: db_changelog
    database-change-log-lock-table: db_changelog_lock
