name: Kotlin CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x spotlessKotlin -x check --no-daemon
      - id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: build/
          compression-level: '1'
  test:
    name: Test with Gradle
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ github.sha }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Check test coverage
        run: ./gradlew koverXmlReport -x test
      - name: Upload test coverage report to CodeCov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
  analyze:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    needs: build
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: java-kotlin
            build-mode: autobuild
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
